### ISSUE TITLE
Telephony (0x0B) missing

### ISSUE THREAD

**Issue by itavero** [nipo/hrdc#2]
I'm planning on making a small USB HID device that makes use of some of the Telephony Devices features (`0x0B`).
Still trying to grasp how the USB HID stuff actually works (been going through the specification, but it's a lot of information to process).

This tool seems like it may help a lot in getting the report descriptor set up correctly, but it seems that the Telephony page is not yet defined.

I was thinking about adding it myself, but it got me wondering if you've added all the definitions so far by hand, instead of maybe generating/converting them from the `dt.ini` and `*.upg` files included with the [HID Descriptor Tool](https://www.usb.org/document-library/hid-descriptor-tool).

**Comment by nipo** [comment]
I didn't want to rely on HIDDT files as I'm not certain I'm allowed to republish them. I could have relied on an external dependency (i.e. make you download the files as part of install procedure), but I cannot assess their long-term availability or their location stability. Including tables internally was less fuss, in the end.

Built-in enums are sugar. You may still use your own definitions, standard or not, in your own descriptor project sources.

Of course, I'm open to contributions that add usage page definitions.

**Comment by itavero** [comment]
My suggestion would be to generate Python files out of those files, so they are only needed to update the generated files.
If I find some time, I'll try to do that (still have to figure out the exact format of the `.upg` files) and create a PR out of it.

**Comment by nipo** [comment]
Thanks !
